config/routes.rb
Rails.application.routes.draw do
  resources :questions do
    resources :answers do
      patch 'accept', on: :member
    end
  end
  resources :comments, except: [ :show, :index, :new]
  devise_for :users, controllers: {
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               registrations: 'users/registrations'
             }             
  root 'questions#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user

  def self.relevant_comments(c_id, c_type)
    Comment.where(commentable_id: c_id, commentable_type: c_type)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /comments/new
  def new
  end

  # GET /comments/1/edit
  def edit
  # saving questions/question_id show page reference
    session[:return_to] = request.referer 
  end

  # POST /comments
  def create
    set_commentable
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_back fallback_location: root_path, notice: 'Comment was successfully posted' }
      else
        format.html { redirect_back fallback_location: root_path, notice: 'Comment failed to get posted' }
      end
    end
  end

  # PATCH /comments/1
  def update
    respond_to do |format|
      if @comment.update(comment_params)
      	format.html { redirect_to session[:return_to], notice: 'Comment was successfully updated' }
      else
        format.html { redirect_back fallback_location: root_path, notice: 'Comment failed to get updated' }
      end
    end
  end

  # DELETE /comments/1
  def destroy
    respond_to do |format|
      if @comment.destroy
        format.html { redirect_back fallback_location: root_path, notice: 'Comment was successfully destroyed' }
      else
      	format.html { redirect_back fallback_location: root_path, notice: 'Comment was not destroyed' }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :commentable_id, :commentable_type)
  end

  def set_commentable
    @comment.commentable_type = params[:comment][:commentable_type]
    @comment.commentable_id = params[:comment][:commentable_id]
  end
end

app/views/comments/_form.html.erb
<div id="comment-box">
  <%= bootstrap_form_for(comment) do |f| %>
    <%= f.text_area :text, rows: "2" %>
    <%= f.hidden_field :commentable_id, value: commentable_id %>
    <%= f.hidden_field :commentable_type, value: commentable_type %>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/comments/_show.html.erb
<% if Comment.relevant_comments(commentable_id, commentable_type).any? %>
  <h3 id="comment">Comments</h3>
  <% Comment.relevant_comments(commentable_id, commentable_type).each do |comment| %>
    <div id="comment">
      <%= comment.text %>
      <% if can? :update, comment %>
        <div>
  	  <%= link_to "edit", edit_comment_path(comment) %>
        </div>
      <% end %>
      <% if can? :delete, comment %>
        <div>
  	  <%= link_to "delete", comment_path(comment), method: :delete %>
        </div>
      <% end %>
    </div>	
    </br>
  <% end %>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>
<div id="comment-box">
  <%= bootstrap_form_for(@comment) do |f| %>
    <%= f.text_area :text, rows: "2" %>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/comments/new.html.erb
<%= render 'form', comment: @comment %>