config/routes.rb
Rails.application.routes.draw do
  resources :questions do
    resources :answers do
      patch 'accept', on: :member
    end
  end
  resources :comments, except: [ :show, :index, :new]
  devise_for :users, controllers: {
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               registrations: 'users/registrations'
             }             
  root 'questions#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  has_many :comments, as: :commentable, dependent: :destroy
  
  validates :user, presence: true
  validates :question, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource :question
  load_and_authorize_resource :answer, through: :question 

  # POST /questions/id/answers
  def create
    @answer.user = current_user
    @answer.question = @question

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @question, notice: "Answer successfully posted" }
      else
        format.html { redirect_to @question, notice: "Answer failed to get posted" }
      end
    end
  end

  # PATCH/PUT /questions/id/answers/1
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @question, notice: 'Answer was successfully updated.' }
      else
        format.html { redirect_to @question, notice: 'Answer failed to get updated' }
      end
    end
  end

  # DELETE /questions/id/answer/id
  def destroy
    respond_to do |format|
      if @answer.destroy
        format.html { redirect_to questions_path, notice: 'Answer was successfully destroyed.' }
      else
        format.html { redirect_to questions_path, notice: 'Answer was not destroyed.' }
      end
    end
  end

  # PATCH /questions/id/answer/id/accept 
  def accept
    respond_to do |format|
      if @question.update(answers_id: params[:id])
        format.html { redirect_to @question, notice: "Answer successfully accepted" }
      else
        format.html { redirect_to @question, notice: "Answer not accepted"}
      end
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:text)
  end
end

app/views/answers/_form.html.erb
<hr>
<h2 id="padding-left"> Your Answer </h2>
<div id="question-block">
  <%= bootstrap_form_for([question, answer]) do |f| %>
    <%= f.text_area :text, rows: "10" %>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/answers/_show.html.erb
<% if @question.answers.any? %>
  <h2 id="padding-left">Answers</h2>
  <hr>
  <div id="answer-block">
    <% @question.answers.each do |answer| %>
      <div id="answer">
        * <%= answer.text %>
        </br>
        <% if (can? :edit, answer) && (can? :delete, answer) %>
      	  <div class="pull-right" id="padding-right">
      	    <%= link_to "delete", question_answer_path(@question, answer), method: :delete,  confirm: "Are you sure?" %>
      	    <%= link_to "edit", edit_question_answer_path(@question, answer) %> 
    	  </div>
        <% end %>
      	<%= render "/comments/show", { commentable_id: answer.id, commentable_type: "Answer" } %>
      	<%= render "/comments/form", { commentable_id: answer.id, comment: Comment.new, 
      		                       commentable_type: "Answer" } %>
        <% if @question.answers_id.nil? %>
          <% if can? :accept, answer %>
            <div class="btn btn-success pull-right">
              <%= link_to "Accept", accept_question_answer_path(@question, answer), method: :patch %>
            </div>
	  <% end %>
        <% else %>
          <h3 class="pull-right">Accepted</h3>	 
        <% end %>	
      </div>	
   <% end %>
  </div>	
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', { answer: @answer, question: @question } %>