config/routes.rb
Rails.application.routes.draw do
  resources :questions do
    resources :answers do
      patch 'accept', on: :member
    end
  end
  resources :comments, except: [ :show, :index, :new]
  devise_for :users, controllers: {
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               registrations: 'users/registrations'
             }             
  root 'questions#index'
end

app/views/layouts/_header.html.erb
<div class="container-fluid">
  <div id="container_custom">
    <nav class="navbar" role="navigation">
      <div class="navbar-header">
	<div class="navbar-brand">
	  <%= link_to image_tag("Stack_Exchange_Logo", size: "200x40"), questions_path  %>
	</div>
      </div>

      <div>
	<form class="navbar-form navbar-right" role="search">
	  <div class="form-group">
	    <input type="text" class="form-control" placeholder="Search Q/A">
	  </div>
	</form>
	<ul class="nav navbar-nav navbar-right">
	  <% if user_signed_in? %>
	    <li class="link_prop padding-top">user <%= current_user.id %></li>
	    <li><%= link_to "log out", destroy_user_session_path, :class => "link_prop", method: :delete %></li>
	  <% else %>
	    <li><%= link_to "log in", new_user_session_path, class: "link_prop" %></li>
	    <li><%= link_to "sign up", new_user_registration_path, class: "link_prop" %></li>
	  <% end %>
	</ul>
      </div>
    </nav>
    
    <div class="row">
      <div class="col-md-4">
      	<%= image_tag("stackoverflow", size: "350x80") %>
      </div>
      <div class="col-md-8"> 
        <button class="btn pull-right"><%= link_to "Questions", questions_path %></button>
        <button class="btn pull-right"><%= link_to "Ask Question", new_question_path %></button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_tabs.html.erb
<div id="container_custom">
  <ul class="nav nav-tabs">
    <li><%= link_to "Log in", session_path("user") %></li> <!-- add sign up path -->
    <li class="active"><%= link_to "Sign up", new_user_registration_path %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
  </div>
  <%= render 'layouts/header'%>
  <%= yield %> 
</body>
</html>